# Generated by Django 3.0.7 on 2020-10-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://www.nicepng.com/png/full/249-2491703_contact-profile-user-default-female-suit-comments-default.png', null=True, upload_to='images', verbose_name='Imagem'),
        ),
    ]
