# Generated by Django 3.0.7 on 2020-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
