# Generated by Django 3.0.7 on 2020-12-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_userwin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWin',
        ),
    ]
