# Generated by Django 3.0.7 on 2020-12-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth_user', '0005_auto_20201220_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitorias',
            new_name='Vitoria',
        ),
    ]
