# Generated by Django 3.0.7 on 2020-12-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth_user', '0006_auto_20201220_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vitoria',
            unique_together={('user', 'room')},
        ),
    ]
