# Generated by Django 3.0.7 on 2020-12-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20201220_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_notification',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
