# Generated by Django 3.0.7 on 2021-02-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_user_token_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_notificarion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
