# Generated by Django 3.0.7 on 2021-02-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_user_token_notificarion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_notificarion',
        ),
    ]
