# Generated by Django 3.0.7 on 2020-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbingo',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
