# Generated by Django 3.0.7 on 2021-02-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbingo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.Room'),
        ),
    ]
