# Generated by Django 3.0.7 on 2020-12-20 13:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_activated', models.BooleanField(default=True)),
                ('is_prox_stack', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Vip', 'Vip'), ('Grátis', 'Grátis')], max_length=10)),
                ('game_iniciado', models.BooleanField(default=False)),
                ('value_card', models.FloatField()),
                ('minumum_quantity', models.IntegerField()),
                ('sorted_numbers', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('finalized', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=3)),
                ('bingo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.Bingo')),
                ('users', models.ManyToManyField(blank=True, default=list, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-value_card'],
            },
        ),
    ]
