# Generated by Django 3.0.7 on 2020-07-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_activated', models.BooleanField(default=True)),
                ('time_initiation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Vip', 'Vip'), ('Grátis', 'Grátis')], max_length=10)),
                ('minumum_quantity', models.IntegerField()),
                ('initiation_game', models.DateTimeField(blank=True, null=True)),
                ('value_card', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bingo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.Bingo')),
                ('users', models.ManyToManyField(blank=True, default=list, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
