# Generated by Django 3.0.7 on 2020-07-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='initiation_game',
            new_name='game_iniciado',
        ),
    ]
