# Generated by Django 3.0.7 on 2020-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attempts',
            field=models.IntegerField(default=3),
        ),
    ]
