# Generated by Django 3.0.7 on 2020-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200626_2138'),
        ('core', '0002_auto_20200626_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='value_card',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, default=list, related_name='roons', to='users.User'),
        ),
    ]
