# Generated by Django 3.0.7 on 2020-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingo',
            name='time_initiation',
        ),
        migrations.AddField(
            model_name='room',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
