# Generated by Django 3.0.7 on 2020-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200626_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='initiation_game',
            field=models.DateTimeField(blank=True),
        ),
    ]
