# Generated by Django 3.0.7 on 2020-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='premium_price',
            field=models.FloatField(default=0),
        ),
    ]
