# Generated by Django 3.0.7 on 2020-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0003_auto_20200626_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='roons', to='users.User'),
        ),
    ]
