# Generated by Django 3.0.7 on 2020-06-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200627_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Bingo',
        ),
    ]
