# Generated by Django 3.0.7 on 2020-10-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200927_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='is_prox_stack',
            field=models.BooleanField(default=False),
        ),
    ]
