# Generated by Django 3.0.7 on 2020-06-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_premium_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='premium_price',
            field=models.FloatField(),
        ),
    ]
