# Generated by Django 3.0.7 on 2020-06-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200630_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='event',
            new_name='bingo',
        ),
    ]
