# Generated by Django 3.0.7 on 2020-06-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200624_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roons', to='core.Event'),
        ),
    ]
