# Generated by Django 3.0.7 on 2020-11-01 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bingo_is_prox_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-value_card']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='closed',
            new_name='finalized',
        ),
        migrations.AddField(
            model_name='room',
            name='sorted_numbers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=11, verbose_name=[{'sorted': False, 'value': 1}, {'sorted': False, 'value': 2}, {'sorted': False, 'value': 3}, {'sorted': False, 'value': 4}, {'sorted': False, 'value': 5}, {'sorted': False, 'value': 6}, {'sorted': False, 'value': 7}, {'sorted': False, 'value': 8}, {'sorted': False, 'value': 9}, {'sorted': False, 'value': 10}, {'sorted': False, 'value': 11}, {'sorted': False, 'value': 12}, {'sorted': False, 'value': 13}, {'sorted': False, 'value': 14}, {'sorted': False, 'value': 15}, {'sorted': False, 'value': 16}, {'sorted': False, 'value': 17}, {'sorted': False, 'value': 18}, {'sorted': False, 'value': 19}, {'sorted': False, 'value': 20}, {'sorted': False, 'value': 21}, {'sorted': False, 'value': 22}, {'sorted': False, 'value': 23}, {'sorted': False, 'value': 24}, {'sorted': False, 'value': 25}]),
            preserve_default=False,
        ),
    ]
