# Generated by Django 3.0.7 on 2020-07-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200630_1325'),
        ('core', '0005_auto_20200630_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bingo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.Bingo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, default=list, related_name='rooms', to='users.User'),
        ),
    ]
