# Generated by Django 3.0.7 on 2020-06-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200626_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roons', to='core.Event'),
        ),
    ]
