# Generated by Django 3.0.7 on 2020-06-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200624_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date',
            new_name='initiation_game',
        ),
        migrations.AddField(
            model_name='room',
            name='minumum_quantity',
            field=models.IntegerField(default=0.0029717682020802376),
            preserve_default=False,
        ),
    ]
