# Generated by Django 3.0.7 on 2020-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200701_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Vip', 'Vip'), ('Grátis', 'Grátis')], max_length=10),
        ),
    ]
