# Generated by Django 3.0.7 on 2020-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201101_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sorted_numbers',
        ),
    ]
