# Generated by Django 3.0.7 on 2020-06-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200624_2228'),
        ('core', '0007_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roons', to='users.User'),
        ),
    ]
