# Generated by Django 3.0.7 on 2020-11-07 14:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_room_sorted_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sorted_numbers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
