# Generated by Django 3.0.7 on 2020-06-26 14:09

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
                ('full_name', models.CharField(max_length=144)),
                ('nick_name', models.CharField(max_length=144, unique=True)),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, verbose_name='CPF')),
                ('phone', models.CharField(max_length=22)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
