# Generated by Django 3.0.7 on 2020-06-26 21:36

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
                ('full_name', models.CharField(max_length=144)),
                ('nick_name', models.CharField(max_length=144, unique=True)),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, verbose_name='CPF')),
                ('phone', models.CharField(max_length=22)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardBingo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activate', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='users.User')),
            ],
        ),
    ]
