# Generated by Django 3.0.7 on 2020-06-26 21:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbingo',
            name='card',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
