# Generated by Django 3.0.7 on 2020-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cardbingo_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbingo',
            name='type',
            field=models.CharField(choices=[('V', 'Vip'), ('G', 'Gratis')], max_length=1),
        ),
    ]
