# Generated by Django 3.0.7 on 2020-06-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200627_1358'),
        ('users', '0003_auto_20200626_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbingo',
            name='type',
        ),
        migrations.AddField(
            model_name='cardbingo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Room'),
        ),
    ]
