# Generated by Django 3.0.7 on 2020-06-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200630_1325'),
        ('users', '0004_auto_20200629_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbingo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.Room'),
        ),
    ]
