# Generated by Django 3.0.7 on 2020-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('cpf', models.CharField(default='', max_length=255)),
                ('conta', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=255)),
                ('banco', models.CharField(blank=True, max_length=144, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
