# Generated by Django 3.0.7 on 2020-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tipo',
            field=models.CharField(choices=[('POUPANÇA', 'Poupança'), ('CORRENTE', 'Corrente')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='validade',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
