# Generated by Django 3.0.7 on 2020-09-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200919_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tipo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
